Major changes to the testing framework.  Currently broken.

diff --git a/tests b/tests
--- a/tests
+++ b/tests
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-function early_fail {
-  echo "Failed to initialize testing.  (${1})" >&2
+function fail {
+  echo "Failure code:  (${1})" >&2
   exit 1
 }
 
@@ -12,58 +12,50 @@ test_dir="/tmp/git-automation_tests"
 master_super_repo="${test_dir}/master_super"
 master_sub_repo="${test_dir}/master_sub"
 master_single_repo="${test_dir}/master_single"
-main_super_repo="${test_dir}/main_super"
-main_sub_repo="${test_dir}/sub_repo"
-sub_sub_repo="${main_super_repo}/sub"
+main_super_repo="${test_dir}/super"
+main_sub_repo="${test_dir}/sub"
+main_single_repo="${test_dir}/single"
+sub_repo_name='sub'
+sub_sub_repo="${main_super_repo}/${sub_repo_name}"
 old_cwd="${PWD}"
 
 test_count=0
 failure_count=0
 success_count=0
 
+function initialize_repo() {
+  master=$1
+  main=$2
+
+  mkdir "${master}"                                             || fail 51
+  cd "${master}"                                                || fail 52
+  git init --bare                                               || fail 53
+
+  git clone "${master}" "${main}"                               || fail 54
+  cd "${main}"                                                  || fail 55
+  touch thing0                                                  || fail 56
+  git add thing0                                                || fail 57
+  git commit -m 'No comment.'                                   || fail 58
+  git push                                                      || fail 59
+}
+
 refresh_test_dir() {
+  oldpwd=$PWD
   rm -rf "${test_dir}"                                          || fail 0
   mkdir "${test_dir}"                                           || fail 1
+  cd "${test_dir}"                                              || fail 2
 
-  mkdir "${master_single_repo}"                                 || fail 2
-  cd "${master_single_repo}"                                    || fail 3
-  git init --bare                                               || fail 4
+  initialize_repo "${master_single_repo}" "${main_single_repo}" || fail 10
+  initialize_repo "${master_super_repo}" "${main_super_repo}"   || fail 11
+  initialize_repo "${master_sub_repo}" "${main_sub_repo}"       || fail 12
 
-  git clone "${master_single_repo}" "${main_single_repo}"       || fail 5
-  cd "${main_single_repo}"                                      || fail 6
-  touch thing0                                                  || fail 7
-  git add thing0                                                || fail 8
-  git commit -m 'No comment.'                                   || fail 9
-  git push                                                      || fail 10
-
-  mkdir "${master_super_repo}"                                  || fail 11
-  cd "${master_super_repo}"                                     || fail 12
-  git init --bare                                               || fail 13
-                                                                         
-  git clone "${master_super_repo}" "${main_super_repo}"         || fail 14
-  cd "${main_super_repo}"                                       || fail 15
-  touch thing0                                                  || fail 16
-  git add thing0                                                || fail 17 
-  git commit -m 'No comment.'                                   || fail 18
-  git push                                                      || fail 19
-                                                                     
-  mkdir "${master_sub_repo}"                                    || fail 20
-  cd "${master_sub_repo}"                                       || fail 21
-  git init --bare                                               || fail 22
-                                                                      
-  git clone "${master_sub_repo}" "${main_sub_repo}"             || fail 23
-  cd "${main_sub_repo}"                                         || fail 24
-  touch thing0                                                  || fail 25
-  git add thing0                                                || fail 26
-  git commit -m 'No comment.'                                   || fail 27
-  git push                                                      || fail 28
-                                                                       
-  cd "${main_super_repo}"                                       || fail 28
-  git submodule add "${master_sub_repo}" "${sub_sub_repo}"      || fail 29
-  git submodule update --init                                   || fail 30
-                                                                        
-  cd "${test_dir}"                                              || fail 31
+  cd "${main_super_repo}"                                       || fail 3
+  git submodule add "${master_sub_repo}" "${sub_repo_name}"     || fail 4
+  git add "${sub_sub_repo}"                                     || fail 5
+  git submodule update --init                                   || fail 6
+  cd $oldpwd
 }
+
 
 for t in api_tests.d/*; do
   if test 'api_tests.d/*' == "${t}"; then
@@ -75,10 +67,11 @@ for t in api_tests.d/*; do
   sc=0
   fc=0
   tc=0
+  refresh_test_dir >/dev/null 2>&1
   while read command; do
     let lineno++
     oldpwd=$PWD
-    cd "${main_super_repo}"
+    cd "${test_dir}"                                            || fail 22
     let tc++
     if eval "${command}" >/dev/null 2>&1; then
       #echo "Pass:  ${test_count}"
@@ -87,7 +80,7 @@ for t in api_tests.d/*; do
       echo "Fail:  ${lineno}"
       let fc++
     fi
-    cd $oldpwd
+    cd $oldpwd                                                  || fail 23
   done < "${t}"
   if test '0' == "${fc}"; then
     let success_count++
