Do not set a version for a repo with no bin/test .  New tests to verify this.  Adjustments and corrections to the testing code.  Display "no version" for a repo with no version in tags.  Comments for tests.  Correct missing 'test' keyword in test 4.

diff --git a/tests/test1_increment_patch b/tests/test1_increment_patch
--- a/tests/test1_increment_patch
+++ b/tests/test1_increment_patch
@@ -1,5 +1,8 @@
+refresh_test_dir true
+
 cd "${repo_single_isolated}"
 
+# Increment automatically.
 touch thing1
 g 'No comment.' automatic > "${output_dir}/1.1.txt" 2>&1
 version="$(get_version "${output_dir}/1.1.txt")"
@@ -7,35 +10,51 @@ if ! test '0.0.1' == "${version}"; then
   return 1
 fi
 
+# Do not increment if nothing changed.
 g 'No comment.' automatic > "${output_dir}/1.2.txt" 2>&1
 version="$(get_version "${output_dir}/1.2.txt")"
 if ! test '0.0.1' == "${version}"; then
   return 2
 fi
 
-
+# Repeat above two tests.
 touch thing2
 g 'No comment.' automatic > "${output_dir}/1.3.txt" 2>&1
 version="$(get_version "${output_dir}/1.3.txt")"
 if ! test "${version}" == '0.0.2'; then
   return 3
 fi
-
 g 'No comment.' automatic > "${output_dir}/1.4.txt" 2>&1
 version="$(get_version "${output_dir}/1.4.txt")"
 if ! test "${version}" == '0.0.2'; then
   return 4
 fi
 
+# Increment manually.
 touch thing3
 g 'No comment.' patch > "${output_dir}/1.5.txt" 2>&1
 version="$(get_version "${output_dir}/1.5.txt")"
 if ! test "${version}" == '0.0.3'; then
   return 5
 fi
-
+# Do not increment if nothing changed.
 g 'No comment.' patch > "${output_dir}/1.6.txt" 2>&1
 version="$(get_version "${output_dir}/1.6.txt")"
 if ! test "${version}" == '0.0.3'; then
   return 6
+fi
+
+# Do not increment if test is failing.
+echo false > bin/test
+touch thing3
+g 'No comment.' automatic > "${output_dir}/1.7.txt" 2>&1
+version="$(get_version "${output_dir}/1.7.txt")"
+if ! test "${version}" == '0.0.3'; then
+  return 7
+fi
+touch thing4
+g 'No comment.' patch > "${output_dir}/1.8.txt" 2>&1
+version="$(get_version "${output_dir}/1.8.txt")"
+if ! test "${version}" == '0.0.3'; then
+  return 8
 fi
diff --git a/tests/test2_increment_minor b/tests/test2_increment_minor
--- a/tests/test2_increment_minor
+++ b/tests/test2_increment_minor
@@ -1,5 +1,8 @@
+refresh_test_dir true
+
 cd "${repo_single_isolated}"
 
+# Increment automatically.
 mkdir -p tests
 echo true > tests/test1
 g 'No comment.' automatic > "${output_dir}/2.1.txt" 2>&1
@@ -7,48 +10,63 @@ version="$(get_version "${output_dir}/2.1.txt")"
 if ! test "${version}" == '0.1.0'; then
   return 1
 fi
-
+# Do not increment if nothing changed.
 g 'No comment.' automatic > "${output_dir}/2.2.txt" 2>&1
 version="$(get_version "${output_dir}/2.2.txt")"
 if ! test "${version}" == '0.1.0'; then
   return 2
 fi
 
+# Repeat above two tests.
 echo true >> tests/test1
 g 'No comment.' automatic > "${output_dir}/2.3.txt" 2>&1
 version="$(get_version "${output_dir}/2.3.txt")"
 if ! test "${version}" == '0.2.0'; then
   return 3
 fi
-
 g 'No comment.' automatic > "${output_dir}/2.4.txt" 2>&1
 version="$(get_version "${output_dir}/2.4.txt")"
 if ! test "${version}" == '0.2.0'; then
   return 4
 fi
 
-echo false > tests/test1
+# Repeat again, adding a test.
+echo true > tests/test2
 g 'No comment.' automatic > "${output_dir}/2.5.txt" 2>&1
 version="$(get_version "${output_dir}/2.5.txt")"
 if ! test "${version}" == '0.3.0'; then
   return 5
 fi
-
 g 'No comment.' automatic > "${output_dir}/2.6.txt" 2>&1
 version="$(get_version "${output_dir}/2.6.txt")"
 if ! test "${version}" == '0.3.0'; then
   return 6
 fi
 
+# Increment manually.
 touch thing1
 g 'No comment.' minor > "${output_dir}/2.7.txt" 2>&1
 version="$(get_version "${output_dir}/2.7.txt")"
 if ! test "${version}" == '0.4.0'; then
   return 7
 fi
-
+# Do not increment if nothing changed.
 g 'No comment.' minor > "${output_dir}/2.8.txt" 2>&1
 version="$(get_version "${output_dir}/2.8.txt")"
 if ! test "${version}" == '0.4.0'; then
   return 8
+fi
+
+# Do not increment if test is failing.
+echo false > bin/test
+g 'No comment.' automatic > "${output_dir}/2.9.txt" 2>&1
+version="$(get_version "${output_dir}/2.9.txt")"
+if ! test "${version}" == '0.4.0'; then
+  return 9
+fi
+touch thing2
+g 'No comment.' minor > "${output_dir}/2.10.txt" 2>&1
+version="$(get_version "${output_dir}/2.10.txt")"
+if ! test "${version}" == '0.4.0'; then
+  return 10
 fi
diff --git a/tests/test3_increment_major b/tests/test3_increment_major
--- a/tests/test3_increment_major
+++ b/tests/test3_increment_major
@@ -1,5 +1,8 @@
+refresh_test_dir true
+
 cd "${repo_single_isolated}"
 
+# Increment automatically.
 mkdir -p tests
 echo true > tests/test1
 g 'No comment.' automatic > "${output_dir}/3.1.1.txt" 2>&1
@@ -9,22 +12,53 @@ version="$(get_version "${output_dir}/3.1.2.txt")"
 if ! test "${version}" == '1.0.0'; then
   return 1
 fi
-
+# Do not increment if nothing changed.
 g 'No comment.' automatic > "${output_dir}/3.2.txt" 2>&1
 version="$(get_version "${output_dir}/3.2.txt")"
 if ! test "${version}" == '1.0.0'; then
   return 2
 fi
 
-touch thing1
-g 'No comment.' major > "${output_dir}/3.3.txt" 2>&1
-version="$(get_version "${output_dir}/3.3.txt")"
+# Repeat above two tests.
+echo true > tests/test1
+g 'No comment.' automatic > "${output_dir}/3.3.1.txt" 2>&1
+rm tests/test1
+g 'No comment.' automatic > "${output_dir}/3.3.2.txt" 2>&1
+version="$(get_version "${output_dir}/3.3.2.txt")"
 if ! test "${version}" == '2.0.0'; then
   return 3
 fi
-
-g 'No comment.' major > "${output_dir}/3.4.txt" 2>&1
+g 'No comment.' automatic > "${output_dir}/3.4.txt" 2>&1
 version="$(get_version "${output_dir}/3.4.txt")"
 if ! test "${version}" == '2.0.0'; then
   return 4
+fi
+
+# Increment manually.
+touch thing1
+g 'No comment.' major > "${output_dir}/3.5.txt" 2>&1
+version="$(get_version "${output_dir}/3.5.txt")"
+if ! test "${version}" == '3.0.0'; then
+  return 5
+fi
+# Do not increment if nothing changed.
+g 'No comment.' major > "${output_dir}/3.6.txt" 2>&1
+version="$(get_version "${output_dir}/3.6.txt")"
+if ! test "${version}" == '3.0.0'; then
+  return 6
+fi
+
+# Do not increment if test is failing.
+echo false > bin/test
+touch thing2
+g 'No comment.' automatic > "${output_dir}/3.7.txt" 2>&1
+version="$(get_version "${output_dir}/3.7.txt")"
+if ! test "${version}" == '3.0.0'; then
+  return 7
+fi
+touch thing3
+g 'No comment.' major > "${output_dir}/3.8.txt" 2>&1
+version="$(get_version "${output_dir}/3.8.txt")"
+if ! test "${version}" == '3.0.0'; then
+  return 8
 fi
